### ISSUE TITLE
xss test

### ISSUE THREAD

**Issue by xxtg666** [xxtg666/xtGitVote-data#10]
JTNDc2NyaXB0JTNFYWxlcnQoJTIyMTE0NTE0JTIyKSUzQy9zY3JpcHQlM0U=
1|MQ==
2|Mg==
**请前往 [这里](https://vote.xxtg666.top) 参加本次投票，请勿手动在此条 issue 下进行 Comment**

**Comment by xxtg666** [comment]
2

**Comment by This-is-XiaoDeng** [comment]
2
